BM2\SiteBundle\Entity\User:
   constraints:
      - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
   properties:
      email:
         - Email: ~

# May not work, according to an old comment this is enforced on road construction, but not on feature construction?
BM2\SiteBundle\Entity\GeoFeature:
   properties:
      name:
         - NotBlank: ~
         - Length:
            min: 3

BM2\SiteBundle\Entity\SettlementPermission:
   properties:
      value:
         - LessThan:
            value: 1000000000
